import Link from 'next/link';

const stages = [
  ['Before work starts', 'If you cancel before document review, filing preparation, or a government payment has started, you may request a refund of the eligible professional fee. Payment-gateway charges and any clearly identified non-refundable charges may be deducted.'],
  ['After review or preparation starts', 'Once the team has reviewed documents, prepared forms, drafted applications, or started professional work, the eligible refund may be reduced because work has already been performed. We will explain the calculation when responding to the request.'],
  ['After government submission or payment', 'Government fees, stamp duty, challans, appointment charges, or other amounts already paid to an authority may not be refundable by NyayLink. A government authority’s rejection or delay does not automatically mean that a professional fee is refundable.'],
  ['If NyayLink cannot continue', 'If we cannot provide the paid service and no government or professional work has started, support will explain the available refund or transfer option. Any remedy depends on the order scope and work already completed.'],
  ['How to request help', 'Email your order number, registered email address, reason for the request, and payment reference to our support team. We will acknowledge the request and explain the next step. Do not send PAN, Aadhaar, passwords, or full bank details by email.'],
];

export default function RefundPolicyPage() {
  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-800">
      <header className="sticky top-0 z-40 bg-[#073B5C] px-4 py-4 text-white shadow sm:px-6"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><Link href="/" className="rounded-xl bg-[#0E7490] px-3 py-1 font-mono text-xl font-black shadow">Nyaya<span className="text-[#F4B942]">Link</span></Link><Link href="/" className="min-h-11 inline-flex items-center text-xs font-bold text-[#F4B942] hover:underline">← Back to home</Link></div></header>
      <main className="mx-auto max-w-4xl space-y-6 px-4 py-8 sm:px-6 sm:py-12"><div className="border-b border-slate-200 pb-5"><p className="text-xs font-bold uppercase tracking-wide text-[#0E7490]">NyayLink policies</p><h1 className="mt-2 text-2xl font-extrabold text-[#073B5C] sm:text-3xl">Cancellation and refund policy</h1><p className="mt-2 text-xs text-slate-500">Last reviewed: August 2026 · Please confirm the final rules with your payment and legal professionals before launch.</p></div><div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-4 text-sm leading-relaxed text-cyan-950"><strong>In simple language:</strong> refund eligibility depends on how much work has already started and whether money has already been paid to a government authority.</div><div className="space-y-5">{stages.map(([title, body], index) => <section key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-base font-extrabold text-[#073B5C]">{index + 1}. {title}</h2><p className="mt-2 text-sm leading-7 text-slate-700">{body}</p></section>)}</div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-base font-extrabold text-[#073B5C]">Refund support</h2><p className="mt-2 text-sm leading-7 text-slate-700">Send your request to <a className="font-bold text-[#0E7490] underline" href="mailto:complain@nyayalink.com">complain@nyayalink.com</a>. General service questions can be sent to <a className="font-bold text-[#0E7490] underline" href="mailto:info@nyayalink.com">info@nyayalink.com</a>.</p></section></main>
    </div>
  );
}
